### PR TITLE
Create dimmer_command.rx

### PR DESCRIPTION
**Pull request by piretro999**

### CODE REVIEW

**Comment by mortommy** [comment]
There an error here, it should be "imposta", and I'm not sure about "smorza", maybe "riduci"?

**Comment by piretro999** [comment]
well, riduci could be quite good but in this case smorza is correct. A synonim could be attenua,

**Comment by mortommy** [comment]
I like "attenua"! It seems more natural.

**Comment by piretro999** [comment]
Attenua is more sophisticated. more current is "smorza", but even more is "abbassa", this is more jargon but common

**Pull request merged**
