### PR TITLE
Added an ability to query for available items

### PR DESCRIPTION
**Pull request by dimaj**
It is helpful to get a list of items that this skill can interact with. This PR is going to surface those items.

### CODE REVIEW

**Comment by mortommy** [comment]
Great!

**Comment by dimaj** [comment]
thanks for merging it in!

what other features might be useful?

**Comment by mortommy** [comment]
What do you think to update the README and USAGE files with the new feature?
Thank you.

**Comment by dimaj** [comment]
Will update as soon as I get home.

**Pull request merged**
